config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :results, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render "index", status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
Home Page

<ul>
  <li><%= link_to "Page 1", root_path(page: 1, filter: params[:filter]) %></li>
  <li><%= link_to "Page 2", root_path(page: 2, filter: params[:filter]) %></li>
  <li><%= link_to "Page 3", root_path(page: 3, filter: params[:filter]) %></li>
  <li><%= link_to "Page 4", root_path(page: 4, filter: params[:filter]) %></li>
</ul>

<ul>
  <li><%= link_to "Dog", root_path(filter: "dog", page: params[:page]) %></li>
  <li><%= link_to "Cat", root_path(filter: "cat", page: params[:page]) %></li>
  <li><%= link_to "Mouse", root_path(filter: "mouse", page: params[:page]) %></li>
  <li><%= link_to "Elephant", root_path(filter: "elephant", page: params[:page]) %></li>
</ul>

<% if params[:page].present? || params[:filter].present? %>
  <h3 style="font-weight: bold; font-size: 14px;">Selected Page and Filters</h3>
  <div>Page: <%= params[:page] %></div>
  <div>Filter: <%= params[:filter] %></div>

  <%= link_to "Show Result", results_path(page: params[:page], filter: params[:filter]) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Formquestion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/results/index.html.erb
<h1 class="font-bold text-2xl">This is the results</h1>


<div>Page: <%= params[:page] %></div>
<div>Filter: <%= params[:filter] %></div>

<%= form_with model: @post, url: results_path(page: params[:page], filter: params[:filter]) do |f| %>
  <% if @post.errors.any? %>
    <div style="color: red; font-weight: bold; padding: 8px;">Oh no there are errors</div>
  <% end %>
  <%= f.text_field :title %>
  <%= f.submit %>
  <%= link_to "cancel", root_path(page: params[:page], filter: params[:filter]) %>
<% end %>